# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=250)),
                ('about_description', models.CharField(max_length=250)),
                ('about_photo', models.ImageField(upload_to=None)),
                ('experience_year', models.CharField(max_length=50)),
                ('about_title2', models.CharField(max_length=250)),
                ('about_description2', models.CharField(max_length=250)),
                ('about_photo2', models.ImageField(upload_to=None)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parallax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parallax_title', models.CharField(max_length=250)),
                ('parallax_description', models.CharField(max_length=250)),
                ('parallax_photo', models.ImageField(upload_to=None)),
                ('parallax_title2_small', models.CharField(max_length=250)),
                ('parallax_title2', models.CharField(max_length=250)),
                ('parallax_description2', models.CharField(max_length=250)),
                ('parallax_photo2', models.ImageField(upload_to=None)),
                ('parallax_row1', models.CharField(max_length=250)),
                ('parallax_row2', models.CharField(max_length=250)),
                ('parallax_row3', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=250)),
                ('service_description', models.CharField(max_length=250)),
                ('service_photo', models.ImageField(upload_to=None)),
                ('service_title2_small', models.CharField(max_length=250)),
                ('service_title2', models.CharField(max_length=250)),
                ('service_description2', models.CharField(max_length=250)),
                ('service_photo2', models.ImageField(upload_to=None)),
                ('service_row1', models.CharField(max_length=250)),
                ('service_row2', models.CharField(max_length=250)),
                ('service_row3', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
